[package]
name = "sgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.5.0"
log = "0.4"
env_logger = "0.11"
memmap2 = "0.9.8"
regex = "1.12.2"
binaryornot = "1.0"

[dependencies.clap]
version = "4.5.48"
features = ["suggestions", "color", "wrap_help", "cargo", "derive"]